name: Publish DockerHub image

on:
  push:
    branches: [ master ]
    tags: [ v* ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
    - uses: docker/metadata-action@v3
      id: meta
      with:
        images: kepawni/apollo-cli
        tags: |
          type=ref,event=branch
          type=sha
          type=sha,prefix={{branch}}-
          type=semver,pattern={{version}}
          type=raw,value=latest
    - uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

